### ISSUE TITLE
Tables configuration_entries and user_users not filled

### ISSUE THREAD

**Issue by mnscholz** [library-data-platform/ldp#213]
When running ldp (with `ldp update -D /var/lib/ldp`), the tables configuration_entries and user_users are not filled. 
Also, the log does not mention the table (excerpt only shows for user):
```
...
Updated table: user_addresstypes [0.1702]
Updated table: user_departments [0.1291]
Updated table: user_groups [0.1577]                                                                                     
Updated table: user_proxiesfor [0.1253]
Completed full update [84.9915]
...
```

I am using Folio Honeysuckle and ldp release 1.1.11 with postgres. I set up ldp according to the guide.

A look into the source code reveals that both tables are the only ones where anonimization seems to take place; see schema.cpp with `table.anonymize = true`.

So I guess it has to do with anonymization.  Am I missing some configuration?

**Comment by nassibnassar** [comment]
Could you confirm if `anonymize` is set in `ldpconf.json`?  See:

https://github.com/library-data-platform/ldp/blob/1.1-release/doc/Admin_Guide.md#7-data-privacy

**Comment by mnscholz** [comment]
`anonymize` wasn't set as it is documented as optional and defaults to true, as I want.

Adding `"anonymize": true` does not change anything, adding `"anonymize": false`, however, populates configuration_entries and user_users! But without anonymization...

**Comment by nassibnassar** [comment]
The reporting community in FOLIO have a group that look at data privacy and GDPR, and they recommended anonymizing the entire user_users table and many fields in other tables ( https://github.com/library-data-platform/ldp/blob/1.1-release/src/anonymize.cpp ).  LDP implements their recommendation.  In 1.1, this is not configurable, but I think it will be in the future.

**Comment by mnscholz** [comment]
Does this mean, that currently the whole user_users table is just left out when anonymization is turned on? This is what effectively happens with my installation.

**Comment by nassibnassar** [comment]
Yes, that is basically right.
