### ISSUE TITLE
publication_period_start and publication_period_end columns in wrong format in inventory_instances table

### ISSUE THREAD

**Issue by sbeltaine** [library-data-platform/ldp#224]
The publication_period_start and publication_period_end columns in the inventory_instances table are in "int8" format instead of a date/time format. Dates are shown as the year with a comma, as in "1,973".

**Comment by nassibnassar** [comment]
The affected columns in `public.inventory_instances` are `publication_period__start` and `publication_period__end`.

**Comment by nassibnassar** [comment]
When I look at `json_extract_path_text(data, 'publicationPeriod', 'start')` and `json_extract_path_text(data, 'publicationPeriod', 'end')`, I see only integers that look like years.  Do you see something different?

**Comment by nassibnassar** [comment]
In the JSON schema, the fields are defined as integers:
```
    "publicationPeriod": {
      "type": "object",
      "description": "Publication period",
      "properties": {
        "start": {
          "type": "integer",
          "description": "Publication start year"
        },
        "end": {
          "type": "integer",
          "description": "Publication end year"
        }
      },
      "additionalProperties": false
    }
```

Closing this issue as the data types appear to be correct.

To remove the commas in DBeaver, select: Preferences > Editors > Data Editor > Data Fornats > Format > Settings > Use grouping > (Uncheck)
