### ISSUE TITLE
data missing on finance_budgets table

### ISSUE THREAD

**Issue by sbeltaine** [library-data-platform/ldp#226]
For both Cornell (on LDP 1.8.2) and Chicago, the **finance_budgets** table is not showing the data consistently for these columns.

allocated
cash_balance
total_funding
available
unavailable
over_expended
over_encumbrance

This is also true for the **budget_t** table in Chicago's implementation of metadb.

**Comment by nassibnassar** [comment]
If you would, please provide a specific example.

**Comment by nassibnassar** [comment]
When I run a query like this one, I do not see a problem:
```
SELECT id,
       cash_balance,
       json_extract_path_text(data, 'cashBalance') AS cash_balance_json
    FROM finance_budgets
    WHERE cash_balance IS NOT NULL OR
        json_extract_path_text(data, 'cashBalance') IS NOT NULL;
```

**Comment by sbeltaine** [comment]
Just to confirm, are you using ldp1_folio_snapshot to test this, and https://folio-snapshot.dev.folio.org/ the front end for this LDP1 instance?

**Comment by nassibnassar** [comment]
I was not able to find a problem in any LDP1 instance.  Could you give a specific example of missing data?

**Comment by sbeltaine** [comment]
You are filtering out NULL values in your test script. The issue is that some fields are displaying NULL values when they should not.

Assuming ldp1_folio_snapshot is using https://folio-snapshot.dev.folio.org/ as its source, you will see this issue for the AFRICAHIST fund in FY23. 

![finance_budgets_issue](https://user-images.githubusercontent.com/36549480/212183634-c99ceabd-0cc5-4bed-8013-1b682f0134c7.PNG)

If you run this quick script in ldp1_folio_snapshot, you will see that the data from the fields mentioned above is NULL and it should be populated with the values you see in FOLIO.

SELECT *
FROM finance_budgets fb
WHERE name LIKE 'AFRICAHIST-FY2023'
;

**Comment by sbeltaine** [comment]
Nancy Bolduc found this issue, so feel free to talk to her in more depth about this problem.

**Comment by nassibnassar** [comment]
Here are the data as they are stored in FOLIO in the `budget` table, which is the source table for `finance_budgets`:
```
 {                                                                
     "id": "d71635df-c08c-49cc-9082-197a30fd0392",                
     "name": "AFRICAHIST-FY2023",                                 
     "fundId": "7fbd5d84-62d1-44c6-9c45-6cb173998bbd",            
     "_version": 17,                                              
     "metadata": {                                                
         "createdDate": "2023-01-12T01:54:36.514Z",               
         "updatedDate": "2023-01-12T18:38:26.774Z",               
         "updatedByUserId": "3cdbc9a2-ea43-5054-9953-69840cccc27d"
     },                                                           
     "acqUnitIds": [                                              
     ],                                                           
     "encumbered": 28.0,                                          
     "allocationTo": 0.0,                                         
     "budgetStatus": "Active",                                    
     "expenditures": 14.0,                                        
     "fiscalYearId": "0bb73cfd-9251-44ce-a7de-3ef16875ba6a",      
     "netTransfers": -2500.0,                                     
     "allocationFrom": 0.0,                                       
     "awaitingPayment": 0.0,                                      
     "initialAllocation": 21000.0,                                
     "allowableEncumbrance": 110.0,                               
     "allowableExpenditure": 100.0                                
 }
```
As you can see, FOLIO is not storing those columns in this table; at least not for this record.

**Comment by sbeltaine** [comment]
Perhaps calculations to another set of stored columns elsewhere?

**Comment by nassibnassar** [comment]
Possibly.  I suggest talking with the PO.

**Comment by NancyBolduc** [comment]
Good morning all!  I find it misleading to have columns in the LDP where the data is not populated.  Why do we have these columns then?

**Comment by nassibnassar** [comment]
For columns transformed from JSON, a column exists if at least one of the records has data.

**Comment by NancyBolduc** [comment]
Okay, that makes sense. So I believe our next step is to work with Folio. Thanks Nassib!
